export {
  Script,
  script,
  stepFor,
  routineFor,
  type CachedPhaseOptions,
  type ClosedPhase,
  type Commit,
  type MountInput,
  type MountOptions,
  type Mounted,
  type OpenPhase,
  type Routine,
  type RunOptions,
} from "./script.js";

export { fileStore, memoryStore } from "./cache.js";

export {
  CacheShapeError,
  DuplicateNameError,
  MissingFlagValueError,
  PromptCancelledError,
  PromptUnavailableError,
  RollbackFailedError,
  SchemaValidationError,
  ScriptAbortedError,
  StepDefinitionError,
  StepFailedError,
  StepTimeoutError,
  UnknownFlagError,
  isAbort,
} from "./errors.js";

export type {
  Awaitable,
  BaseFlagOptions,
  BooleanFlagOptions,
  CacheHandle,
  CacheMode,
  CacheOptions,
  CacheSource,
  CacheStore,
  CachedEntry,
  CleanField,
  Cleaned,
  ConfirmPromptOptions,
  LogPlacement,
  Merge,
  MultiSelectPromptOptions,
  PhaseOptions,
  PhaseStatus,
  Prettify,
  ProgressHandle,
  PromptChoice,
  PromptHandle,
  RetryPolicy,
  RollbackContext,
  RollbackData,
  RollbackReport,
  RunResult,
  RunStatus,
  ScriptOptions,
  SelectPromptOptions,
  SlotValue,
  StaleContext,
  StepContext,
  StepDef,
  InheritedKeyStepDef,
  StepReport,
  StepStatus,
  StringFlagOptions,
  TaskHandle,
  TaskListHandle,
  TextPromptOptions,
  UnknownFlags,
  UnknownSlots,
  WithStepFor,
} from "./types.js";

export { formatDuration } from "./state.js";
export { setColorEnabled, isColorEnabled } from "./ui/ansi.js";
export { palette, symbols } from "./ui/theme.js";
